headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Polo Mistral\\Desktop\\kinesia-app\\.claude\\worktrees\\adoring-merkle-1dda14\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Polo Mistral\\Desktop\\kinesia-app\\.claude\\worktrees\\adoring-merkle-1dda14"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/workbox-*.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/registerSW.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"